# Generated by Django 6.0.4 on 2026-04-18 02:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WSP', 'WhatsApp'), ('YAPE', 'Yape / Plin'), ('TRANS', 'Transferencia Bancaria')], default='WSP', max_length=10, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Pagado / Verificado'),
        ),
    ]
