# Generated by Django 6.0.4 on 2026-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_payment_method_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Verificación'), ('COMPLETED', 'Completado / Entregado'), ('CANCELLED', 'Cancelado / Devuelto')], default='PENDING', max_length=10, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='¿Está Pagado?'),
        ),
    ]
